bezpAp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('my_messages.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_messages/urls.py
from django.conf.urls import url

from . import views

app_name = 'my_messages'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^messages/$', views.all_messages, name='all_messages'),
    url(r'^messages/add/$', views.add_message, name='add_message'),
    url(r'^messages/delete/(?P<pk>[0-9]+)/$', views.delete_message, name='delete_message'),
    url(r'^messages/edit/(?P<pk>[0-9]+)/$', views.edit_message, name='edit_message'),
    url(r'^messages/(?P<pk>[0-9]+)/editors/$', views.message_editors, name='message_editors'),
]

my_messages/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    title = models.CharField("Title", max_length=50, null=False, blank=False)
    content = models.TextField("Content", max_length=200, null=False, blank=False)
    date = models.DateTimeField("Date", default=datetime.now, null=True, blank=True)
    user = models.ForeignKey(User, related_name="Creator", null=True, blank=True, on_delete=models.SET_NULL)
    editors = models.ManyToManyField(User, related_name="Editors", blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Message"
        verbose_name_plural = "Messages"

my_messages/forms.py
from django import forms

from my_messages.models import *


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['title', 'content']


class MessagePermissionsForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['editors']

my_messages/views.py
import logging

from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.utils import timezone

from .forms import MessageForm, MessagePermissionsForm
from .models import Message

now = timezone.now()
logger = logging.getLogger(__name__)


@login_required
def index(self):
    return redirect('my_messages:all_messages')


@login_required
def all_messages(request):
    messages = Message.objects.all()
    return render(request, 'my_messages/all_messages.html', {'messages': messages, 'user': request.user})


def login_view(request):
    form_class = AuthenticationForm
    template_name = 'my_messages/login.html'

    if request.method == 'POST':
        form = form_class(data=request.POST)
        form.fields['password'].label = "Password"
        form.fields['username'].label = "Username"
        if form.is_valid():
            user = form.get_user()
            if user is not None:
                login(request, user)
                return redirect('my_messages:index')
    else:
        form = form_class()
        form.fields['password'].label = "Password"
        form.fields['username'].label = "Username"
    return render(request, template_name, {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('my_messages:index')


@login_required
def add_message(request):
    form_class = MessageForm
    template_name = 'my_messages/add_message.html'
    form = form_class(request.POST or None)
    if request.POST and form.is_valid():
        message = form.save(commit=False)
        message.user = request.user
        message.save()
        return redirect('my_messages:all_messages')
    return render(request, template_name, {'form': form})


@login_required
def delete_message(**kwargs):
    query = Message.objects.get(id=kwargs['pk']).first()
    query.delete()
    return redirect('my_messages:all_messages')


@login_required
def message_editors(request, **kwargs):
    form_class = MessagePermissionsForm
    template_name = 'my_messages/message_permissions.html'
    message = Message.objects.filter(id=kwargs['pk']).first()
    form = form_class(request.POST or None, instance=message)
    form.fields["editors"].queryset = User.objects.exclude(id=message.user.id)
    print(User.objects.exclude(id=message.user.id))
    if request.POST and form.is_valid():
        message = form.save(commit=False)
        editors = form.cleaned_data['editors']
        message.editors.set(editors)
        message.save()
        return redirect('my_messages:all_messages')
    return render(request, template_name, {'form': form})


@login_required
def edit_message(request, **kwargs):
    form_class = MessageForm
    template_name = 'my_messages/add_message.html'
    message = Message.objects.filter(id=kwargs['pk']).first()
    form = form_class(request.POST or None, instance=message)
    if request.POST and form.is_valid():
        message = form.save(commit=False)
        message.save()
        return redirect('my_messages:all_messages')
    return render(request, template_name, {'form': form})

my_messages/templates/my_messages/add_message.html
{% extends "my_messages/base.html" %}

{% block content %}
<section id="registration">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto">

                <h2>Add new message</h2>
                <hr/>
                <br/>
                <form action="" class="form-horizontal" method="post" role="form">
                    {% csrf_token %}
                    {% include 'my_messages/includes/form_template.html' %}

                    <div class="form-group">
                        <div class="p-l-5 offset-lg-3 col-lg-9 offset-sm-5 col-sm-7">
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>

{% endblock %}

my_messages/templates/my_messages/all_messages.html
{% extends "my_messages/base.html" %}

{% block content %}

<div class="container m-t-15">
    <div class="row">
        <div class="col-lg-10 mx-auto">
              <span class="float-right">
                  <a class="link-decoration-none" href="{% url 'my_messages:add_message' %}">
                      <button class="btn btn-success m-b-10">Add</button>
                  </a>
              </span>
            {% for message in messages %}
            <h4>{{ message }}
                {% if user in message.editors.all %}
                <a class="link-decoration-none" href="{% url 'my_messages:edit_message' message.id %}">
                    <button class="btn btn-warning">Change</button>
                </a>
                {% endif %}
                {% if message.user == user %}
                <a class="link-decoration-none" href="{% url 'my_messages:edit_message' message.id %}">
                    <button class="btn btn-warning">Change</button>
                </a>
                <a class="link-decoration-none"
                   href="{% url 'my_messages:delete_message' message.id %}" onclick="return confirm('Are you sure?')">
                    <button class="btn btn-danger">Remove</button>
                </a>
                <a class="link-decoration-none" href="{% url 'my_messages:message_editors' message.id %}">
                    <button class="btn btn-info">Editors</button>
                </a>
                {% endif %}
            </h4>
            <span class="small">{{ message.date }}</span>
            <p class="m-t-10">{{ message.content }}</p>
            <div class="text-right">~{{ message.user }}</div>
            <hr/>
            {% endfor %}
            <br/>
        </div>
    </div>
</div>

{% endblock %}

my_messages/templates/my_messages/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Messages</title>
    {% load staticfiles %}

    {% block extra_head_base %}
    {% block extra_head %}{% endblock %}
    {% endblock %}

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/scrolling-nav.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cuprum" rel="stylesheet">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
</head>
<body id="page-top">

{% include "my_messages/includes/header.html" %}

{% if request.get_full_path == "/messages/" %}
<header class="bg-container text-white text-center">
    <h2>Messages</h2>
</header>
{% endif %}

<br/>

<div class="">
    {% block content %}
    {% endblock %}
</div>

<footer class="bg-dark">
    <div class="container">
        <p class="m-t-15 text-center text-white f-14">Copyright &copy; Ewelina Ruchlewicz 2019</p>
    </div>
</footer>

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/scrolling-nav.js' %}"></script>

{% block extra_body_base %}
{% block extra_body %}{% endblock %}
{% endblock %}

</body>
</html>

my_messages/templates/my_messages/includes/form_template.html
{% load widget_tweaks %}
{% for field in form %}
<div class="form-group row">
    <label class="medium-bold col-form-label col-xs-12 col-sm-3 col-lg-3">{{ field.label_tag }}</label>
    <div class="col-xs-12 col-sm-7 col-lg-5">
        {{ field|attr:"class:form-control" }}
    </div>
    <span class="text-danger small">{{ field.errors }}</span>
    <span class="offset-lg-3 offset-sm-5 f-10 gray p-l-15">{{ field.help_text }}</span>
</div>
{% endfor %}

my_messages/templates/my_messages/includes/header.html
{% block content %}
{% load staticfiles %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'my_messages:all_messages' %}" id="logo">Messages</a>
        <button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler" data-target="#navbarResponsive" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if request.get_full_path == "/" %}
                {% endif %}
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'my_messages:login' %}"
                       name="login_href">Login</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <span class="nav-link js-scroll-trigger bold">Hello, {{ request.user.username }}!</span>
                </li>
                {% endif %}

                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'my_messages:logout' %}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

my_messages/templates/my_messages/login.html
{% extends "my_messages/base.html" %}

{% block content %}
<section class="p-b-10" id="login">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto">

                <h2>Login</h2>
                <hr/>
                <br/>
                <form action="" class="form-horizontal" method="post" role="form">
                    {% csrf_token %}
                    {% include 'my_messages/includes/form_template.html' %}

                    <div class="form-group">
                        <div class="p-l-5 offset-lg-3 col-lg-10 offset-sm-3 col-sm-9">
                            <button class="btn btn-primary" id="login_btn" type="submit">Login</button>
                        </div>
                    </div>
                </form>
                <br/><br/>
            </div>
        </div>
    </div>
</section>

{% endblock %}

my_messages/templates/my_messages/message_permissions.html
{% extends "my_messages/base.html" %}

{% block content %}
<section id="registration">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto">

                <h2>Change editors</h2>
                <hr/>
                <br/>
                <form action="" class="form-horizontal" method="post" role="form">
                    {% csrf_token %}
                    {% include 'my_messages/includes/form_template.html' %}

                    <div class="form-group">
                        <div class="p-l-5 offset-lg-3 col-lg-9 offset-sm-5 col-sm-7">
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</section>

{% endblock %}